IC2: #分组标签，可自定义创建
  settings:
    isReplace: true
    #是否没收方块并将其替换为其他方块，可减少服务器负担，但会破坏游戏体验
    #若填true则应写对应的new，将消耗导线且被替换成新物品
    #若填false则返还手中导线
  old: #方块ID-方块子ID
    - 1-100
    - 1-200
    - 1-300
  new: 5-0
  #当触发回路时提示消息
  message: 此导线不可连接为回路，已没收
MEK:
  settings:
    isReplace: false
  old:
    - 1-400
    - 1-500
    - 1-600
  message: 此导线不可连接为回路，已返还